name: .NET 7 Build and Release

on:
 workflow_dispatch 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build with dotnet
      run: dotnet publish --configuration Release --output out

    # Assuming you're zipping the output for release; adjust if necessary.
    - name: Zip the output
      run: zip -r Odido-authenticator.zip ./out/

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: ./Odido-authenticator.zip
