name: .NET 7 Build and Release

on:
 - workflow_dispatch 
 - push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build with dotnet
      run: dotnet publish --configuration Release --output out

    - name: Log MD5 hashes of files in out
      run: |
        Get-ChildItem -Path out -Recurse | ForEach-Object {
          $md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
          $hash = [System.BitConverter]::ToString($md5.ComputeHash([System.IO.File]::ReadAllBytes($_.FullName)))
          Write-Output "$($_.Name) - $hash"

    # Assuming you're zipping the output for release; adjust if necessary.
    - name: Zip contents of out using 7z
      run: 7z a Odido-Authenticator.zip out\*

      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Odido-Authenticator
        path: ./out
  
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
       files: Odido-Authenticator.zip
